name: "Pull Request: Validate"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  pr-metadata:
    uses: MichaelSp/kassio/.github/workflows/pr-metadata.yaml@main

  pre-commit-check:
    uses: MichaelSp/kassio/.github/workflows/pre-commit-check.yaml@main
    needs:
      - pr-metadata
    with:
      modifiedFiles: ${{ needs.pr-metadata.outputs.addedOrModifiedFiles }}

  charts-changelog:
    uses: MichaelSp/kassio/.github/workflows/charts-changelog.yaml@main
    permissions:
      contents: write
    needs:
      - pr-metadata
      - pre-commit-check
    with:
      isRenovatePR: ${{ needs.pr-metadata.outputs.isRenovatePR }}
      modifiedCharts: ${{ needs.pr-metadata.outputs.addedOrModifiedCharts }}

  charts-lint:
    uses: MichaelSp/kassio/.github/workflows/charts-lint.yaml@main
    needs:
      - pr-metadata
      - charts-changelog
    with:
      checkoutCommit: ${{ needs.charts-changelog.outputs.commitHash }}
      chartChangesDetected: ${{ needs.pr-metadata.outputs.addedOrModified }}

  charts-test:
    uses: MichaelSp/kassio/.github/workflows/charts-test.yaml@main
    needs:
      - pr-metadata
      - charts-changelog
    with:
      checkoutCommit: ${{ needs.charts-changelog.outputs.commitHash }}
      chartChangesDetected: ${{ needs.pr-metadata.outputs.addedOrModified }}
